### ISSUE TITLE
Xcode warning

### ISSUE THREAD

**Issue by Aynnor** [SDWebImage/SDWebImageFLPlugin#10]
### Description
```bash
SingleTestProject/Pods/Pods.xcodeproj MobileCoreServices has been renamed. Use CoreServices instead.
```

**Comment by Aynnor** [comment]
so should remove MobileCoreServices framework and add CoreServices framework ?

**Comment by dreampiggy** [comment]
If you do so, you'll be un-compatible with iOS 8~10.

Because this **Renaming** happended after iOS 11. iOS 10 System framework does not have anything naming `CoreServices` and will cause dyld load crash.
